title: Your Site Name
description: Your site description
baseurl: ""
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Custom settings
search: true

sass:
  sass_dir: _sass
  style: compressed
